#
# Access and Login control
#
admin_home:
    path:     /
    defaults: { _controller: AdminBundle:Views:index }
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Views:loginform }
admin_logout:
    path:     /logout
admin_register_form:
    path:     /register_form
    defaults: { _controller: AdminBundle:Views:registerform }
admin_register:
    path:     /register
    defaults: { _controller: AdminBundle:Admin:register }
admin_recover_form:
    path:     /recover_form
    defaults: { _controller: AdminBundle:Views:recoverform }
admin_recover:
    path:     /recover
    defaults: { _controller: AdminBundle:Admin:recover }
admin_confirmation:
    path:     /confirmation/{token}
    defaults: { _controller: AdminBundle:Views:mailConfirmation }
admin_checkavailability:
    path:     /checkavailability
    defaults: { _controller: AdminBundle:Admin:checkAvailability }
admin_resetpassword_form:
    path:     /resetpassword/{token}
    defaults: { _controller: AdminBundle:Views:resetPassword }
admin_resetandlogin:
    path:     /resetandlogin
    defaults: { _controller: AdminBundle:Admin:resetAndLogin }
admin_createandloginuser:
    path:     /createandlogin
    defaults: { _controller: AdminBundle:Admin:createAndLogin }

#
# Users administration
#
admin_manage_users:
    path:     /manageusers
    defaults: { _controller: AdminBundle:Views:users }
admin_createuser_form:
    path:     /createuser_form
    defaults: { _controller: AdminBundle:Views:userForm }
admin_createuser:
    path:     /createuser
    defaults: { _controller: AdminBundle:Admin:createUser }
admin_edituser_form:
    path:     /edituser_form
    defaults: { _controller: AdminBundle:Views:userForm }
admin_edituser:
    path:     /edituser
    defaults: { _controller: AdminBundle:Admin:editUser }
admin_deleteuser:
    path:     /deleteuser
    defaults: { _controller: AdminBundle:Admin:deleteUser }

#
# Test
#
admin_test_template:
    path:     /testtemplate
    defaults: { _controller: AdminBundle:Views:testTemplate }