admin_home:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }
admin_login:
    path:     /login
    defaults: { _controller: AdminBundle:Admin:login }
admin_logout:
    path:     /logout

admin_createuser_view_test:
    path:     /bd/user
    defaults: { _controller: AdminBundle:Views:user }
admin_createworker_view_test:
    path:     /bd/worker
    defaults: { _controller: AdminBundle:Views:worker }
admin_createclient_view_test:
    path:     /bd/client
    defaults: { _controller: AdminBundle:Views:client }
admin_createservice_view_test:
    path:     /bd/service
    defaults: { _controller: AdminBundle:Views:service }

#
# Users administration
#
admin_manage_users:
    path:     /manageusers
    defaults: { _controller: AdminBundle:Views:users }
admin_createuser_form:
    path:     /createuser_form
    defaults: { _controller: AdminBundle:Views:userForm }
admin_createuser:
    path:     /createuser
    defaults: { _controller: AdminBundle:Admin:createUser }
admin_edituser_form:
    path:     /edituser_form
    defaults: { _controller: AdminBundle:Views:userForm }
admin_edituser:
    path:     /edituser
    defaults: { _controller: AdminBundle:Admin:editUser }
admin_deleteuser:
    path:     /deleteuser
    defaults: { _controller: AdminBundle:Admin:deleteUser }

#
# Groups administration
#
admin_manage_services:
    path:     /manageservices
    defaults: { _controller: AdminBundle:Views:services }
admin_createservice_form:
    path:     /createservice_form
    defaults: { _controller: AdminBundle:Views:serviceForm }
admin_createservice:
    path:     /createservice
    defaults: { _controller: AdminBundle:Admin:createService }
admin_editservice_form:
    path:     /editservice_form
    defaults: { _controller: AdminBundle:Views:serviceForm }
admin_editservice:
    path:     /editservice
    defaults: { _controller: AdminBundle:Admin:editService }
admin_deleteservice:
    path:     /deleteservice
    defaults: { _controller: AdminBundle:Admin:deleteService }
    
#
# Categories administration
#
admin_manage_categories:
    path:     /managecategories
    defaults: { _controller: AdminBundle:Views:categories }
admin_createcategory_form:
    path:     /createcategory_form
    defaults: { _controller: AdminBundle:Views:categoryForm }
admin_createcategory:
    path:     /createcategory
    defaults: { _controller: AdminBundle:Admin:createCategory }
admin_editcategory_form:
    path:     /editcategory_form
    defaults: { _controller: AdminBundle:Views:categoryForm }
admin_editcategory:
    path:     /editcategory
    defaults: { _controller: AdminBundle:Admin:editCategory }
admin_deletecategory:
    path:     /deletecategory
    defaults: { _controller: AdminBundle:Admin:deleteCategory }

#
# Car merchandises administration
#
admin_manage_models:
    path:     /managemodels
    defaults: { _controller: AdminBundle:Views:models }
admin_createmodel_form:
    path:     /createmodel_form
    defaults: { _controller: AdminBundle:Views:modelForm }
admin_createmodel:
    path:     /createmodel
    defaults: { _controller: AdminBundle:Admin:createModel }
admin_editmodel_form:
    path:     /editmodel_form
    defaults: { _controller: AdminBundle:Views:modelForm }
admin_editmodel:
    path:     /editmodel
    defaults: { _controller: AdminBundle:Admin:editModel }
admin_deletemodel:
    path:     /deletemodel
    defaults: { _controller: AdminBundle:Admin:deleteModel }

#
# Merchandises administration
#
admin_manage_merchandises:
    path:     /managemerchandises
    defaults: { _controller: AdminBundle:Views:merchandises }
admin_createmerchandise_form:
    path:     /createmerchandise_form
    defaults: { _controller: AdminBundle:Views:merchandiseForm }
admin_createmerchandise:
    path:     /createmerchandise
    defaults: { _controller: AdminBundle:Admin:editMerchandise }
admin_editmerchandise_form:
    path:     /editmerchandise_form
    defaults: { _controller: AdminBundle:Views:merchandiseForm }
admin_editmerchandise:
    path:     /editmerchandise
    defaults: { _controller: AdminBundle:Admin:editMerchandise }
admin_deletemerchandise:
    path:     /deletemerchandise
    defaults: { _controller: AdminBundle:Admin:deleteMerchandise }