calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /calendar

app_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app_card:
    resource: "@VirtualCardBundle/Resources/config/routing.yml"
    prefix:   /card

app:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /home
    