calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /calendar

app_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /realtors