<?php

namespace AdminBundle\Repository;

/**
 * BrandModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandModelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDuplicates($array) {
        $qb = $this->createQueryBuilder('u')
                ->where('u.brand = :brand')
                ->andWhere('u.type = :type')
                ->andWhere('u.name = :name')
                ->andWhere('u.id <> :id')
                ->setParameter('brand', $array['brand'])
                ->setParameter('type', $array['type'])
                ->setParameter('name', $array['name'])
                ->setParameter('id', $array['id']);
        return $qb->getQuery()->getResult();
    }
    
    public function deleteByIds($array) {
        $qb = $this->createQueryBuilder('u')
                ->delete()
                ->where('u.id in (:list)')
                ->setParameter('list', $array);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
