<?php

namespace AdminBundle\Repository;

/**
 * CarBrandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
