<?php

namespace CoreBundle\Repository;

/**
 * AdvisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvisorRepository extends \Doctrine\ORM\EntityRepository
{
}
