<?php

namespace CoreBundle\Repository;

/**
 * BusinessWorkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessWorkerRepository extends \Doctrine\ORM\EntityRepository
{
}
