<?php

namespace CoreBundle\Repository;

/**
 * CardTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
