<?php

namespace CoreBundle\Repository;

/**
 * MerchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchandiseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDuplicates($array) {
        $qb = $this->createQueryBuilder('u')
                ->where('u.service = :service')
                ->andwhere('u.cartype = :cartype')
                ->andWhere('u.id <> :id')
                ->setParameter('service', $array['service'])
                ->setParameter('cartype', $array['cartype'])
                ->setParameter('id', $array['id']);
        return $qb->getQuery()->getResult();
    }
    
    public function deleteByIds($array) {
        $qb = $this->createQueryBuilder('u')
                ->delete()
                ->where('u.id in (:list)')
                ->setParameter('list', $array);
        return $qb->getQuery()->getSingleScalarResult();
    }
}
