<?php

namespace CoreBundle\Repository;

/**
 * RealtorGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealtorGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
