<?php

namespace CoreBundle\Repository;

/**
 * RealtorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealtorRepository extends \Doctrine\ORM\EntityRepository
{
}
