<?php

namespace AdminBundle\Repository;

/**
 * RegisterRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegisterRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
